choco install -y vcredist2005 vcredist2008 vcredist2010 vcredist2012 vcredist2013 vcredist2015 vcredist2017 xna31
choco install -y googlechrome
choco install -y firefox
choco install -y jdk8
choco install -y adobereader
choco install -y 7zip.install
choco install -y notepadplusplus.install
choco install -y git.install
choco install -y vlc
choco install -y aimp
choco install -y ccleaner
choco install -y powershell
choco install -y sysinternals
choco install -y putty.install
choco install -y virtualbox
choco install -y dropbox
choco install -y python2
choco install -y irfanview
choco install -y cdburnerxp
choco install -y svn
choco install -y evernote
choco install -y steam
choco install -y qbittorrent
choco install -y ffmpeg
choco install -y wincdemu
choco install -y everything
choco install -y handbrake.install
